version: '3'
services:
  mongo:
    image: mongo
    container_name: 'ncnews-mongo'
    restart: always
    volumes:
      - mongo:/var/lib/mongo
    networks:
      - northcoders-news

  ncnews-be:
    container_name: 'ncnews-server'
    build:
      context: .
      args:
        - NPM_TOKEN
    command: /bin/sh -c 'npm install && node seed/seed.js && npm start'
    environment:
      NPM_TOKEN: ${NPM_TOKEN}
    volumes:
      - ./:/app:delegated
      - node_modules:/app/node_modules
    ports:
      - '8000:8000'
    networks:
      - northcoders-news

volumes:
  mongo:
  node_modules:

networks:
  northcoders-news:
    external:
      name: northcoders-news
